### ISSUE TITLE
how does it work when deploying on heroku ?

### ISSUE THREAD

**Issue by luvpreetsingh** [henriquebastos/python-decouple#48]
I am using it in my django project. Runs perfect on my local machine.

But it is causing problems when deploying on heroku,

    Traceback (most recent call last):
      File "manage.py", line 22, in <module>
        execute_from_command_line(sys.argv)
      File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
        settings.INSTALLED_APPS
      File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
        self._setup(name)
      File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
        self._wrapped = Settings(settings_module)
      File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
      File "/app/weather/settings.py", line 20, in <module>
        API_KEY = config('API_KEY')
      File "/app/.heroku/python/lib/python3.6/site-packages/decouple.py", line 197, in __call__
         return self.config(*args, **kwargs)
      File "/app/.heroku/python/lib/python3.6/site-packages/decouple.py", line 85, in __call__
        return self.get(*args, **kwargs)
      File "/app/.heroku/python/lib/python3.6/site-packages/decouple.py", line 70, in get
        raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
    decouple.UndefinedValueError: API_KEY not found. Declare it as envvar or define a default value.

I am getting this error when running `heroku run python manage.py migrate`

What should be done ?

**Comment by henriquebastos** [comment]
It seems you forgot to add the setting to your heroku envionment before
deploying. Fix it doing:

```
heroku config:set API_KEY=THERIGHTPRODUCTIONVALUE
```

**Comment by luvpreetsingh** [comment]
Actually, I think the right way to deploy on heroku is to OS env vars.

instead of 

    from decouple import config
    api_key = config('api_key')

The .ini OR .env file is always in .gitignore. So, it can't read variables stored in untracked files.

it is better to use,

    export api_key="therightvalue"
and then, 

   import os 
   api_key = os.environ.get('api_key')

This way, it can easily use heroku config vars as the dyno environment is also linux and we dont need to change anything.

**Comment by henriquebastos** [comment]
But **that is** the purpose of `python-decouple`.

The line `API_KEY = config('API_KEY')` reads from `os.environ` and if it's not there it tries `.env` or `settings.ini`.

So with a **single** settings.py you can have **multiple** instances of your app _(dev, production, stage, demo1, demoN, etc)_

If you use `os.environ` directly you'll have a harder time to have a single `settings.py` for you project.

**Comment by henriquebastos** [comment]
Also, decouple have the `cast` argument that saves a lot of time converting strings. Check out the README for details.
